tfausak/witch

- src/lib/Witch.hs
> Add documentation about typed Template Haskell

- src/lib/Witch/Instances.hs
- src/test/Main.hs
> Add instances to convert try cast exceptions into strings

- src/lib/Witch/Instances.hs
- src/lib/Witch/TryCastException.hs
- src/lib/Witch/Utility.hs
- src/test/Main.hs
> Add original exception to try cast exception

- src/lib/Witch.hs
- src/lib/Witch/Instances.hs
- src/lib/Witch/Utility.hs
> Add helper functions for defining `tryCast`

- src/lib/Witch/Instances.hs
> Use `float2Double` instead of `realToFrac`

- src/lib/Witch.hs
- src/lib/Witch/Casting.hs
- src/test/Main.hs
- witch.cabal
> Add `Casting` type for deriving classes via

- src/lib/Witch.hs
- src/lib/Witch/TryCast.hs
- src/lib/Witch/Utility.hs
> Improve documentation

- src/lib/Witch/Instances.hs
> Add identity `From` instance

- .github/workflows/ci.yaml
- .gitignore
- witch.cabal
> Add support for GHC 8.6, 8.4, and 8.2

- .github/workflows/ci.yaml
- src/lib/Witch/Instances.hs
- src/test/Main.hs
This relates to #26. It is the same as #30, but it incorporates the changes from #31.
> I386 take two

- src/lib/Witch/Instances.hs
- src/test/Main.hs
> Add more instances for string types

- src/lib/Witch/Instances.hs
- src/test/Main.hs
> Convert between `Fixed` and `Rational`

- .github/workflows/ci.yaml
- witch.cabal
This might fix #41, or it might fail.
> Support GHC 9.2.1

- src/lib/Witch.hs
> Add some laws

- src/lib/Witch/Instances.hs
- src/test/Main.hs
> Fix floating point conversions

- .github/workflows/ci.yaml
- witch.cabal
This is to build with the `lts-17.0` Stackage resolver.
> Allow HUnit 1.6.1

- source/library/Witch/Encoding.hs
- source/library/Witch/Instances.hs
- source/test-suite/Main.hs
Part of #66. Basically the same as #70.
> Add UTF-32LE encoding

- source/library/Witch/Encoding.hs
- source/library/Witch/Instances.hs
- source/test-suite/Main.hs
Part of #66. Basically the same as #72.
> Add UTF-32BE encoding

- source/library/Witch.hs
> Re-export encodings

- .github/workflows/workflow.yaml
- source/library/Witch.hs
- source/library/Witch/From.hs
- witch.cabal
https://github.com/tfausak/haskell-packages/pull/3
> Add support for GHC 9.6.1

- .devcontainer.json
- .devcontainer/compose.yaml
- .devcontainer/devcontainer.json
- .github/workflows/workflow.yaml
- compose.yaml
- witch.cabal
https://github.com/tfausak/haskell-packages/pull/15
> Upgrade to GHC 9.8.1

- witch.cabal
https://github.com/commercialhaskell/stackage/issues/7216
> Allow bytestring 0.12

- witch.cabal
> Allow containers 0.7

- witch.cabal
https://github.com/tfausak/witch/compare/1.2.1.1...7e7cd448cfc1939f525590317476c3a342bbfc01
> Version 1.2.2.0

- source/library/Witch.hs
> Fix documentation for encodings

- .github/workflows/ci.yml
- witch.cabal
> Add support for GHC 9.12, drop support for GHC 9.6

- source/library/Witch/Instances.hs
I should have done this as part of #85.
> Remove obsolete workarounds

- .github/workflows/ci.yml
> Attempt to work around Cabal bug

- .github/workflows/ci.yml
> Combine release jobs
